receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8889']

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    # Removido o bloco de resource_to_telemetry_conversion para evitar duplicação de rótulos
  logging:
    verbosity: detailed

processors:
  batch:
    timeout: 5s

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777

service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheus, logging]  # Exportador 'logging' está configurado aqui
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]  # Certifique-se de que o exportador 'logging' esteja referenciado corretamente

  extensions: [health_check, pprof]
