global:
  scrape_interval: 15s  # Intervalo de coleta das métricas

scrape_configs:
  - job_name: 'opentelemetry-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']  # Aponta para o OpenTelemetry Collector

  - job_name: 'grafana-tempo'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['tempo:3200']